import os 

os.environ['VERIFY_TOKEN'] = "SDJGIENKFJ66665"
os.environ['PAGE_ACCESS_TOKEN'] = "EAAH2jdKoLmwBAJby7ZAr4ZArtqCwrsBpRnBuk7BJTvhmiq9dScDuxv7bTuurfYwaC5taoA7JarnEhGfLweQdNAHGFXNDdLd25DTFncc6LnBM2bXmcA3ZCtnabQcZBRFX0d4BtZB5PldZCUvqJBO3MSZARBjMS6UkmygKpZAXxIsNSAZDZD"

os.environ['DATABASE_URL'] = 'postgresql://TESTUSER:TESTING@LOCALHOST/TEST_APP'